In [1]:
import cv2
import numpy as np
import os
from sklearn.neighbors import KNeighborsClassifier

In [2]:
files = [faces for faces in  os.listdir('dataset') if faces.endswith('.npy') ]
names = [faces[:-4] for faces in files]
print(names)

face_data = []

for filename in files:
    data = np.load('dataset/' + filename)
    print(data.shape)
    face_data.append(data)

face_data=np.array(face_data)
print(face_data.shape)
print(names)
face_data = np.concatenate(face_data ,axis = 0)
print(face_data.shape)
names = np.repeat(names ,300)
print(names.shape)
names = names.reshape((names.shape[0],1))
print(names.shape)
dataset = np.hstack((face_data, names))
print(dataset.shape)

['AB DeVilliers', 'Virat Kolhi']
(300, 30000)
(300, 30000)
(2, 300, 30000)
['AB DeVilliers', 'Virat Kolhi']
(600, 30000)
(600,)
(600, 1)
(600, 30001)


In [3]:
face_pred=KNeighborsClassifier()

In [4]:
face_pred.fit(dataset[:, :-1] , dataset[:,-1])

c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:755: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  estimator=estimator)
c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\neighbors\_base.py:399: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [5]:
cap=cv2.VideoCapture('video_test/abd and virat.mp4') #video location or 0 for video stream from webcam
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_alt.xml')

while True:
    ret , frame = cap.read() # Status , Frame
    if not ret:
        continue
    # Find All the faces in the frame
    faces = face_cascade.detectMultiScale(frame , 1.3 ,5) # Frame , scaling factor , neighbors

        
    print(faces)

    for face in faces:
        x,y,w,h = face
        face_selection = frame[y:y+h , x:x+w]
        print(face_selection.shape)
        # cv2.imshow("Face_selection", face_selection)
        face_selection = cv2.resize(face_selection,(100,100))
        print(face_selection.shape)
        face_cropped = face_selection.reshape((1,-1))
        print(face_cropped.shape)
        
        pred=face_pred.predict(face_cropped)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),5) # Frame , start pos , end pos , color , thickness
        cv2.putText(frame , pred[0] , (x,y),cv2.FONT_HERSHEY_SIMPLEX , 1 ,(255,255,255),2)
    cv2.imshow("Feed" , frame)
    key = cv2.waitKey(1)
    if key & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[[666 144 130 130]]
(130, 130, 3)
(100, 100, 3)
(1, 30000)
[[660 144 137 137]]
(137, 137, 3)
(100, 100, 3)
(1, 30000)
[[659 145 132 132]]
(132, 132, 3)
(100, 100, 3)
(1, 30000)
[[663 149 124 124]]
(124, 124, 3)
(100, 100, 3)
(1, 30000)
[[666 152 120 120]]
(120, 120, 3)
(100, 100, 3)
(1, 30000)
[[667 150 122 122]]
(122, 122, 3)
(100, 100, 3)
(1, 30000)
[[655 143 140 140]]
(140, 140, 3)
(100, 100, 3)
(1, 30000)
[[653 140 150 150]]
(150, 150, 3)
(100, 100, 3)
(1, 30000)
[[665 148 125 125]]
(125, 125, 3)
(100, 100, 3)
(1, 30000)
[[662 144 132 132]]
(132, 132, 3)
(100, 100, 3)
(1, 30000)
[[664 145 125 125]]
(125, 125, 3)
(100, 100, 3)
(1, 30000)
[[668 145 123 123]]
(123, 123, 3)
(100, 100, 3)
(1, 30000)
[[670 145 122 122]]
(122, 122, 3)
(100, 100, 3)
(1, 30000)
[[666 140 134 134]]
(134, 134, 3)
(100, 100, 3)
(1, 30000)
[[664 137 142 142]]
(142, 142, 3)
(100, 100, 3)
(1, 30000)
[[662 136 143 143]]
(143, 143, 3)
(100, 100, 3)
(1, 30000)
[[665 139 135 135]]
(135, 135, 3)
(100, 100, 3)
(1, 3000

[[678 177 142 142]
 [391 149 139 139]]
(142, 142, 3)
(100, 100, 3)
(1, 30000)
(139, 139, 3)
(100, 100, 3)
(1, 30000)
[[677 173 152 152]
 [387 146 146 146]]
(152, 152, 3)
(100, 100, 3)
(1, 30000)
(146, 146, 3)
(100, 100, 3)
(1, 30000)
[[675 171 155 155]
 [385 145 150 150]]
(155, 155, 3)
(100, 100, 3)
(1, 30000)
(150, 150, 3)
(100, 100, 3)
(1, 30000)
[[672 166 166 166]
 [385 147 145 145]]
(166, 166, 3)
(100, 100, 3)
(1, 30000)
(145, 145, 3)
(100, 100, 3)
(1, 30000)
[[670 162 172 172]
 [382 147 150 150]]
(172, 172, 3)
(100, 100, 3)
(1, 30000)
(150, 150, 3)
(100, 100, 3)
(1, 30000)
[[674 159 170 170]
 [994 555  51  51]
 [382 148 149 149]]
(170, 170, 3)
(100, 100, 3)
(1, 30000)
(51, 51, 3)
(100, 100, 3)
(1, 30000)
(149, 149, 3)
(100, 100, 3)
(1, 30000)
[[677 159 169 169]
 [380 150 148 148]]
(169, 169, 3)
(100, 100, 3)
(1, 30000)
(148, 148, 3)
(100, 100, 3)
(1, 30000)
[[685 158 166 166]
 [380 151 144 144]]
(166, 166, 3)
(100, 100, 3)
(1, 30000)
(144, 144, 3)
(100, 100, 3)
(1, 30000)
[[683 14

[[622 167 194 194]
 [300 143 184 184]]
(194, 194, 3)
(100, 100, 3)
(1, 30000)
(184, 184, 3)
(100, 100, 3)
(1, 30000)
[[625 174 184 184]
 [296 145 183 183]]
(184, 184, 3)
(100, 100, 3)
(1, 30000)
(183, 183, 3)
(100, 100, 3)
(1, 30000)
[[288 143 184 184]
 [621 166 199 199]]
(184, 184, 3)
(100, 100, 3)
(1, 30000)
(199, 199, 3)
(100, 100, 3)
(1, 30000)
[[284 140 188 188]
 [611 165 205 205]]
(188, 188, 3)
(100, 100, 3)
(1, 30000)
(205, 205, 3)
(100, 100, 3)
(1, 30000)
[[278 143 187 187]
 [611 166 204 204]]
(187, 187, 3)
(100, 100, 3)
(1, 30000)
(204, 204, 3)
(100, 100, 3)
(1, 30000)
[[270 140 190 190]
 [613 167 200 200]]
(190, 190, 3)
(100, 100, 3)
(1, 30000)
(200, 200, 3)
(100, 100, 3)
(1, 30000)
[[263 139 191 191]
 [601 166 208 208]]
(191, 191, 3)
(100, 100, 3)
(1, 30000)
(208, 208, 3)
(100, 100, 3)
(1, 30000)
[[246 132 209 209]
 [591 154 228 228]]
(209, 209, 3)
(100, 100, 3)
(1, 30000)
(228, 228, 3)
(100, 100, 3)
(1, 30000)
[[601 160 219 219]
 [236 127 211 211]]
(219, 219, 3)
(100, 100, 

[[642 151 194 194]]
(194, 194, 3)
(100, 100, 3)
(1, 30000)
[[649 155 184 184]
 [357 129 179 179]]
(184, 184, 3)
(100, 100, 3)
(1, 30000)
(179, 179, 3)
(100, 100, 3)
(1, 30000)
[[643 151 198 198]
 [361 125 185 185]]
(198, 198, 3)
(100, 100, 3)
(1, 30000)
(185, 185, 3)
(100, 100, 3)
(1, 30000)
[[643 152 196 196]
 [364 127 179 179]]
(196, 196, 3)
(100, 100, 3)
(1, 30000)
(179, 179, 3)
(100, 100, 3)
(1, 30000)
[[365 122 185 185]]
(185, 185, 3)
(100, 100, 3)
(1, 30000)
[[362 114 200 200]]
(200, 200, 3)
(100, 100, 3)
(1, 30000)
[[373 122 183 183]]
(183, 183, 3)
(100, 100, 3)
(1, 30000)
[[377 121 177 177]]
(177, 177, 3)
(100, 100, 3)
(1, 30000)
[[372 118 188 188]]
(188, 188, 3)
(100, 100, 3)
(1, 30000)
[[379 125 174 174]]
(174, 174, 3)
(100, 100, 3)
(1, 30000)
[[380 123 179 179]]
(179, 179, 3)
(100, 100, 3)
(1, 30000)
[[386 125 170 170]]
(170, 170, 3)
(100, 100, 3)
(1, 30000)
[[390 121 177 177]]
(177, 177, 3)
(100, 100, 3)
(1, 30000)
[[392 118 179 179]]
(179, 179, 3)
(100, 100, 3)
(1, 30000)


[[921 158 199 199]
 [298 163 188 188]]
(199, 199, 3)
(100, 100, 3)
(1, 30000)
(188, 188, 3)
(100, 100, 3)
(1, 30000)
[[912 164 189 189]
 [294 160 196 196]]
(189, 189, 3)
(100, 100, 3)
(1, 30000)
(196, 196, 3)
(100, 100, 3)
(1, 30000)
[[297 163 188 188]
 [893 174 188 188]]
(188, 188, 3)
(100, 100, 3)
(1, 30000)
(188, 188, 3)
(100, 100, 3)
(1, 30000)
[[296 163 190 190]
 [869 170 197 197]]
(190, 190, 3)
(100, 100, 3)
(1, 30000)
(197, 197, 3)
(100, 100, 3)
(1, 30000)
[[298 164 188 188]
 [851 173 191 191]]
(188, 188, 3)
(100, 100, 3)
(1, 30000)
(191, 191, 3)
(100, 100, 3)
(1, 30000)
[[302 168 183 183]
 [836 180 184 184]]
(183, 183, 3)
(100, 100, 3)
(1, 30000)
(184, 184, 3)
(100, 100, 3)
(1, 30000)
[[302 165 190 190]]
(190, 190, 3)
(100, 100, 3)
(1, 30000)
[[304 168 183 183]
 [790 186 191 191]]
(183, 183, 3)
(100, 100, 3)
(1, 30000)
(191, 191, 3)
(100, 100, 3)
(1, 30000)
[[306 170 182 182]]
(182, 182, 3)
(100, 100, 3)
(1, 30000)
[[307 167 185 185]]
(185, 185, 3)
(100, 100, 3)
(1, 30000)
[[30

[[329 116 176 176]
 [770 132 244 244]]
(176, 176, 3)
(100, 100, 3)
(1, 30000)
(244, 244, 3)
(100, 100, 3)
(1, 30000)
[[325 115 184 184]]
(184, 184, 3)
(100, 100, 3)
(1, 30000)
[[329 117 178 178]]
(178, 178, 3)
(100, 100, 3)
(1, 30000)
[[326 118 180 180]]
(180, 180, 3)
(100, 100, 3)
(1, 30000)
[[327 120 176 176]]
(176, 176, 3)
(100, 100, 3)
(1, 30000)
[[326 122 178 178]]
(178, 178, 3)
(100, 100, 3)
(1, 30000)
[[329 123 171 171]]
(171, 171, 3)
(100, 100, 3)
(1, 30000)
[[327 124 174 174]]
(174, 174, 3)
(100, 100, 3)
(1, 30000)
[[324 123 177 177]]
(177, 177, 3)
(100, 100, 3)
(1, 30000)
[[320 118 186 186]]
(186, 186, 3)
(100, 100, 3)
(1, 30000)
[[321 119 179 179]]
(179, 179, 3)
(100, 100, 3)
(1, 30000)
[[316 119 184 184]]
(184, 184, 3)
(100, 100, 3)
(1, 30000)
[[320 121 178 178]]
(178, 178, 3)
(100, 100, 3)
(1, 30000)
[[323 129 165 165]]
(165, 165, 3)
(100, 100, 3)
(1, 30000)
[[323 125 171 171]]
(171, 171, 3)
(100, 100, 3)
(1, 30000)
[[661 141 244 244]
 [321 125 175 175]]
(244, 244, 3)
(100